# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c22bfc557f4d93ac07359bb2b07183463e40424d2f8955c9dd2e2b9a2e0697fd87b042d67fc36f446cca33d9a0fe31b2cf4374cc94c82ad9dc0b4ab083ede986

test:
  secret_key_base: bb004642b2eab1d1cf9f08a37d694931a82aa076af0d838c4ace74cc690230100a0796f37eabb6b1dddf8a8e4221eba9be8ececb9326bec5bc75b2a6db5230d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
